### ISSUE TITLE
Errors during installation with composer 

### ISSUE THREAD

**Issue by loic425** [akeneo/pim-community-standard#145]
When Installing pim project with composer using this command line : 

php composer.phar create-project --prefer-dist akeneo/pim-community-standard ./pim-project "1.3.*@stable",

We have the following errors :

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle
 instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle
 instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle
 instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle i
nstead.
Package friendsofsymfony/rest is abandoned, you should avoid using it. No replac
ement was suggested.

**Comment by grena** [comment]
Hello @loic425, thank you for the report.
We are aware of those **warnings** during installation of the PIM.
It's due to some old dependencies we rely on, we plan to upgrade these, but there is no ETA yet.

Please note that the PIM is still fully functional as they are just "warning informations" ;)

Kind regards,

**Comment by loic425** [comment]
@grena Ok thanks a lot.
